//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Services.Drv.Emera3.Culture {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sys.Services.Drv.Emera3.Culture.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коррестировка времени кнопками.
        /// </summary>
        internal static string ADJUSTMENT_TIME_BUTTONS {
            get {
                return ResourceManager.GetString("ADJUSTMENT_TIME_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коррестировка времени по каналам связи.
        /// </summary>
        internal static string ADJUSTMENT_TIME_CHANNELS {
            get {
                return ResourceManager.GetString("ADJUSTMENT_TIME_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение администратора.
        /// </summary>
        internal static string ADMIN_RESET {
            get {
                return ResourceManager.GetString("ADMIN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза А:откл.
        /// </summary>
        internal static string AOFF {
            get {
                return ResourceManager.GetString("AOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза А:вкл.
        /// </summary>
        internal static string AON {
            get {
                return ResourceManager.GetString("AON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибочный аргумент.
        /// </summary>
        internal static string ARGUMENT {
            get {
                return ResourceManager.GetString("ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (авто.расчет сезона лето).
        /// </summary>
        internal static string AUTO_CALC_SUMMER_SEASON {
            get {
                return ResourceManager.GetString("AUTO_CALC_SUMMER_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (авто.расчет сезона зима).
        /// </summary>
        internal static string AUTO_CALC_WINTER_SEASON {
            get {
                return ResourceManager.GetString("AUTO_CALC_WINTER_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Блок поврежден.
        /// </summary>
        internal static string BLOCK_DAMAGED {
            get {
                return ResourceManager.GetString("BLOCK_DAMAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза B:откл.
        /// </summary>
        internal static string BOFF {
            get {
                return ResourceManager.GetString("BOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза B:вкл.
        /// </summary>
        internal static string BON {
            get {
                return ResourceManager.GetString("BON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обрыв цепей ABC напряжения U или (и) тока I. .
        /// </summary>
        internal static string CHAIN_TERM {
            get {
                return ResourceManager.GetString("CHAIN_TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение пароля.
        /// </summary>
        internal static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение параметров телеметрии.
        /// </summary>
        internal static string CHANGE_SET_TELEMETRY {
            get {
                return ResourceManager.GetString("CHANGE_SET_TELEMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение констант.
        /// </summary>
        internal static string CHANGING_CONSTANTS {
            get {
                return ResourceManager.GetString("CHANGING_CONSTANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение даты переключения сезонов.
        /// </summary>
        internal static string CHANGING_DATE_CHANGE_SEASONS {
            get {
                return ResourceManager.GetString("CHANGING_DATE_CHANGE_SEASONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (зав. номер).
        /// </summary>
        internal static string CHG_ID {
            get {
                return ResourceManager.GetString("CHG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (номер пользователя).
        /// </summary>
        internal static string CHG_ID_USER {
            get {
                return ResourceManager.GetString("CHG_ID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (KI KU или формат отображения).
        /// </summary>
        internal static string CHG_KI_KU_FORMAT {
            get {
                return ResourceManager.GetString("CHG_KI_KU_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (маска отображения).
        /// </summary>
        internal static string CHG_MASK_VIEW {
            get {
                return ResourceManager.GetString("CHG_MASK_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (сетевой адрес).
        /// </summary>
        internal static string CHG_NET_ID {
            get {
                return ResourceManager.GetString("CHG_NET_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (параметры порта).
        /// </summary>
        internal static string CHG_PORT_SETT {
            get {
                return ResourceManager.GetString("CHG_PORT_SETT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (тип прибора).
        /// </summary>
        internal static string CHG_TYPE_EQUIPMENT {
            get {
                return ResourceManager.GetString("CHG_TYPE_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие крышки счетчика.
        /// </summary>
        internal static string CLOSING_COUNTER {
            get {
                return ResourceManager.GetString("CLOSING_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза C:откл.
        /// </summary>
        internal static string COFF {
            get {
                return ResourceManager.GetString("COFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза C:вкл.
        /// </summary>
        internal static string CON {
            get {
                return ResourceManager.GetString("CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка контрольной суммы.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поврежен файл калибровки.
        /// </summary>
        internal static string DAMAGE_CALIBRATION_FILE {
            get {
                return ResourceManager.GetString("DAMAGE_CALIBRATION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Неисправно EEPROM 1).
        /// </summary>
        internal static string DEFECTIVE_EEPROM_1 {
            get {
                return ResourceManager.GetString("DEFECTIVE_EEPROM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Неисправно EEPROM 2).
        /// </summary>
        internal static string DEFECTIVE_EEPROM_2 {
            get {
                return ResourceManager.GetString("DEFECTIVE_EEPROM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Неисправно OЗУ).
        /// </summary>
        internal static string DEFECTIVE_OZU {
            get {
                return ResourceManager.GetString("DEFECTIVE_OZU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Неисправно ПЗУ).
        /// </summary>
        internal static string DEFECTIVE_PZU {
            get {
                return ResourceManager.GetString("DEFECTIVE_PZU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счетчик занят.
        /// </summary>
        internal static string DEVICE_BUSY {
            get {
                return ResourceManager.GetString("DEVICE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрошенный срез отличается от полученного. Возможно это связано с неточным временем.
        /// </summary>
        internal static string ERROR_CUT {
            get {
                return ResourceManager.GetString("ERROR_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Ошибка DSP).
        /// </summary>
        internal static string ERROR_DSP {
            get {
                return ResourceManager.GetString("ERROR_DSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Ошибка обмена с DSP).
        /// </summary>
        internal static string ERROR_EXCHANGE_DSP {
            get {
                return ResourceManager.GetString("ERROR_EXCHANGE_DSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал событий.
        /// </summary>
        internal static string EVENTS_DESC {
            get {
                return ResourceManager.GetString("EVENTS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная функция.
        /// </summary>
        internal static string FUNCTION {
            get {
                return ResourceManager.GetString("FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мгновенные значения.
        /// </summary>
        internal static string IM_DESC {
            get {
                return ResourceManager.GetString("IM_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат пакета.
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (режим калибровки).
        /// </summary>
        internal static string M_CALIBRATE {
            get {
                return ResourceManager.GetString("M_CALIBRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (нормальный режим).
        /// </summary>
        internal static string M_NORM {
            get {
                return ResourceManager.GetString("M_NORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (режим поверки).
        /// </summary>
        internal static string M_VERIFICATION {
            get {
                return ResourceManager.GetString("M_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аппаратная ошибка.
        /// </summary>
        internal static string MACHINE_ERROR {
            get {
                return ResourceManager.GetString("MACHINE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнуление максимальной мощности.
        /// </summary>
        internal static string MAX_POWER_RESET {
            get {
                return ResourceManager.GetString("MAX_POWER_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка памяти.
        /// </summary>
        internal static string MEMORY_ERROR {
            get {
                return ResourceManager.GetString("MEMORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение режима.
        /// </summary>
        internal static string MODE_CHANGE {
            get {
                return ResourceManager.GetString("MODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помехи в сети.
        /// </summary>
        internal static string NETWORK_PROBLEMS {
            get {
                return ResourceManager.GetString("NETWORK_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не соответствие запрошенного и ответившего сетевого адреса.
        /// </summary>
        internal static string NOT_COMPLIANT_ADDRESS {
            get {
                return ResourceManager.GetString("NOT_COMPLIANT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не соответствие запрошенной и ответившей функции.
        /// </summary>
        internal static string NOT_COMPLIANT_FUNCTION {
            get {
                return ResourceManager.GetString("NOT_COMPLIANT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая конфигурация не позволяет выполнение команды.
        /// </summary>
        internal static string NOT_CORRESPOND_TO_CONFIG {
            get {
                return ResourceManager.GetString("NOT_CORRESPOND_TO_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибор &apos;{0}&apos; не подерживает параметр {1}, дискретность {2}{3}. Рекомендуем обновить прошивку прибора.
        /// </summary>
        internal static string NOT_PARAM {
            get {
                return ResourceManager.GetString("NOT_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие крышки счетчика.
        /// </summary>
        internal static string OPENING_COUNTER {
            get {
                return ResourceManager.GetString("OPENING_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для работы с оптопортом нажмите кнопку Доступ.
        /// </summary>
        internal static string OPTOPORT_ERROR {
            get {
                return ResourceManager.GetString("OPTOPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ненормальная длина пакета.
        /// </summary>
        internal static string PACKET_LENGTH_ABNORMAL {
            get {
                return ResourceManager.GetString("PACKET_LENGTH_ABNORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный параметр.
        /// </summary>
        internal static string PARAMETER {
            get {
                return ResourceManager.GetString("PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнуление энергии.
        /// </summary>
        internal static string POWER_RESET {
            get {
                return ResourceManager.GetString("POWER_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (накопленный).
        /// </summary>
        internal static string PR_ACCUM {
            get {
                return ResourceManager.GetString("PR_ACCUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (суточный).
        /// </summary>
        internal static string PR_DAY {
            get {
                return ResourceManager.GetString("PR_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (месячный).
        /// </summary>
        internal static string PR_MONTH {
            get {
                return ResourceManager.GetString("PR_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (годовой).
        /// </summary>
        internal static string PR_YEAR {
            get {
                return ResourceManager.GetString("PR_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение мгновенных значений. Результат: {0}.
        /// </summary>
        internal static string READ_IM {
            get {
                return ResourceManager.GetString("READ_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение 30-и минутных.
        /// </summary>
        internal static string Read30Min {
            get {
                return ResourceManager.GetString("Read30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение 3-х минутных.
        /// </summary>
        internal static string Read3Min {
            get {
                return ResourceManager.GetString("Read3Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение суточных.
        /// </summary>
        internal static string ReadDay {
            get {
                return ResourceManager.GetString("ReadDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение дыр: От времени {0} Глубиной:{1} До макс.времени:{2} =&gt;выч.нач.время:{3} дыр:{4}.
        /// </summary>
        internal static string ReadHoles {
            get {
                return ResourceManager.GetString("ReadHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение KU:{0}.
        /// </summary>
        internal static string ReadKU {
            get {
                return ResourceManager.GetString("ReadKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение месячных.
        /// </summary>
        internal static string ReadMonth {
            get {
                return ResourceManager.GetString("ReadMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение годовых.
        /// </summary>
        internal static string ReadYear {
            get {
                return ResourceManager.GetString("ReadYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение расписания выходных дней.
        /// </summary>
        internal static string RESCHEDULE_HOLIDAYS {
            get {
                return ResourceManager.GetString("RESCHEDULE_HOLIDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сканирование пароля.
        /// </summary>
        internal static string SCAN_PASSWORD {
            get {
                return ResourceManager.GetString("SCAN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (сезона лето).
        /// </summary>
        internal static string SEASON_SUMMER {
            get {
                return ResourceManager.GetString("SEASON_SUMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (сезона зима).
        /// </summary>
        internal static string SEASON_WINTER {
            get {
                return ResourceManager.GetString("SEASON_WINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнуление срезов.
        /// </summary>
        internal static string SEGMENTS_RESET {
            get {
                return ResourceManager.GetString("SEGMENTS_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синхронизация архива.
        /// </summary>
        internal static string SYNC_ARCH {
            get {
                return ResourceManager.GetString("SYNC_ARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение тарифного расписания.
        /// </summary>
        internal static string TARIFF_SCHEDULE_CHANGE {
            get {
                return ResourceManager.GetString("TARIFF_SCHEDULE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключение защиты.
        /// </summary>
        internal static string Test_DisableProtection {
            get {
                return ResourceManager.GetString("Test_DisableProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение времени.
        /// </summary>
        internal static string Test_DT {
            get {
                return ResourceManager.GetString("Test_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка границ архива.
        /// </summary>
        internal static string Test_Error_Req {
            get {
                return ResourceManager.GetString("Test_Error_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение коэф..
        /// </summary>
        internal static string Test_KIKU {
            get {
                return ResourceManager.GetString("Test_KIKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение коэф. преобразования.
        /// </summary>
        internal static string Test_KPr {
            get {
                return ResourceManager.GetString("Test_KPr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение серийного номера.
        /// </summary>
        internal static string Test_SN {
            get {
                return ResourceManager.GetString("Test_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение версии.
        /// </summary>
        internal static string Test_SV {
            get {
                return ResourceManager.GetString("Test_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбой часов реального времени.
        /// </summary>
        internal static string TIME_CLOCK_FAILTURE {
            get {
                return ResourceManager.GetString("TIME_CLOCK_FAILTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустиммая тарифная программа.
        /// </summary>
        internal static string UNACCEPTABLE_TARIFF {
            get {
                return ResourceManager.GetString("UNACCEPTABLE_TARIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Несанкционированный доступ.
        /// </summary>
        internal static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (для выходных).
        /// </summary>
        internal static string WEEKEND_DAYS {
            get {
                return ResourceManager.GetString("WEEKEND_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (для рабочих дней).
        /// </summary>
        internal static string WORKING_DAYS {
            get {
                return ResourceManager.GetString("WORKING_DAYS", resourceCulture);
            }
        }
    }
}
